export { default as CreateNote } from './CreateNote/CreateNote'
export { default as Photo } from './Photo/Photo'
export { default as Group } from './Group/Group'
export { default as FormEdit } from './EditNote/components/FormEdit'
export { default as EditNote } from './EditNote/EditNote'
export { default as EditNoteLayout } from './EditNote/EditNoteLayout'
export { default as UserProfile } from './UserProfile/UserProfile'
export { default as AnonymousMessage } from './AnonymousMess/AnonymousMessage'
export { default as Sketch } from './Sketch/Sketch'
export { default as Dustbin } from './Dustbin/Dustbin'

export { default as Home } from './Home'
export { default as UserSetting } from './UserSetting'
